### ISSUE TITLE
Can't play rock paper scissors, even with correct inputs, games just loops printing starting statements without checking for inputs 

### ISSUE THREAD

**Issue by MANUSRAO** [Prajwalprakash3722/games#1]
I worked out solution for many errors:
1. Uploaded code has wrong indentation hence, only print and input statements gets printed with no checking
2. It doesn't have any loop exit condition ``player = False`` is not changed anywhere instead ``sys.exit(0)`` is used which causes abrupt stopping of run instead change code to make ``player = True``
3.  Please refactor code to show computer moves also 
4.  Not an issue, but instead of ``randint`` use ``choice`` to get random value from the list 
If possible please allow me to clear this issue in your code or correct the issues yourself.
Thank You

**Comment by Prajwalprakash3722** [comment]
Okay @MANUSRAO I shall look into it again, In the mean time make a PR.

**Comment by Prajwalprakash3722** [comment]
have already updated the branch in patch-1  and also already merged the patch-1 to the main, Thank you for pointing the correction.

Is there any issue or shall I close this issue?

**Comment by MANUSRAO** [comment]
I'm okay with correction, but still some small problems persists ,
* You can still avoid ``sys.exit(0)`` and use ``player_move = True``
* For the code you have used ``player_move`` in two different cases 1. Input and 2. For while loop checking 
*  Also you can use ``.lower()`` while taking input and modifying that in ``list v`` to avoid case sensitive errors
I would request you to assign me this issue if possible? Or you could correct it them yourself and close this issue. Thank You

**Comment by Prajwalprakash3722** [comment]
> I'm okay with correction, but still some small problems persists ,
> 
> * You can still avoid ``sys.exit(0)`` and use ``player_move = True``
> 
> * For the code you have used ``player_move`` in two different cases 1. Input and 2. For while loop checking 
> 
> *  Also you can use ``.lower()`` while taking input and modifying that in ``list v`` to avoid case sensitive errors
> 
> I would request you to assign me this issue if possible? Or you could correct it them yourself and close this issue. Thank You

The issue has been already assigned

**Comment by MANUSRAO** [comment]
@Prajwalprakash3722 check once when i inputed in smallcases it discarded the inputs
